### ISSUE TITLE
checksum issues

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#110]
What are typical causes of checksum test failures?  Too rapid reading?

```python
Traceback (most recent call last):
  File "/usr/local/friskby/bin/fby_client", line 139, in run
    sampler.collect()
  File "/usr/local/friskby/lib/sampler.py", line 34, in collect
    pm10, pm25 = self.reader.read()
  File "/usr/local/friskby/lib/sds011.py", line 47, in read
    raise Exception("Checksum test failed")
Exception: Checksum test failed
```

@joakim-hove @njberland

**Comment by joakim-hove** [comment]
Multiple concurrent reads?

**Comment by pgdr** [comment]
No, single threaded, one instance of RPiParticle installed and running ...

**Comment by joakim-hove** [comment]
Test and active service?

**Comment by pgdr** [comment]
No testing, just my sensor doing its sensing, in production.  I'll see if it might be hardware related ...

**Comment by pgdr** [comment]
Hasn't happened in a while.  Perhaps the hardware had a bad week.
