### ISSUE TITLE
local and remote configs

### ISSUE THREAD

**Issue by semafor** [FriskByBergen/RPiParticle#118]
Proposal:
Have a `friskby_device.settings` that configures the local system, i.e. the sampler, submitter, controlpanel and DAO. This can be be separate from the `friskby_server.settings` that contains the API key, API URL and maybe a API `minimum_versions` setting that require clients to e.g. have `requests==9.1` installed.

**Comment by semafor** [comment]
Another advantage could be that the sensor device path (e.g. `/dev/usb/foo1`) could be configurable until we have automatic detection.

**Comment by pgdr** [comment]
Fixed.
