### ISSUE TITLE
Does not install systemd files?

### ISSUE THREAD

**Issue by joakim-hove** [FriskByBergen/RPiParticle#135]
When I do: `sudo python setup.py install` it does not seem like any systemd files are installed; is that correct? And I would also guess a `systemd deamon-reload`should be issued somewhere?

**Comment by pgdr** [comment]
Can you try `pip install .`?

Or `setup.py bdist_wheel`
the problem might be related to source distribution.

**Comment by joakim-hove** [comment]
OK `pip install` worked.

**Comment by semafor** [comment]
I think the problem is that travis isn't building wheels. And that a complete installation is not possible using a source distribution (it should). However, pip is making it very hard to distribute arbitrary files using a source distribution.

**Comment by pgdr** [comment]
I'm closing this as `pip install` is working.
