### ISSUE TITLE
Error in updateClient method

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#73]
```
Traceback (most recent call last):
  File "/usr/local/friskby/bin/fby_client", line 110, in run
    self.updateClient()
TypeError: updateClient() takes exactly 2 arguments (1 given)
```

Will make PR in a couple of hours if nobody beats me to it.

Gone climbing.

**Comment by joakim-hove** [comment]
Thanks - but fixed: https://github.com/FriskByBergen/RPiParticle/pull/71

**Comment by pgdr** [comment]
You're coding faster than the speed of light

**Comment by pgdr** [comment]
But how come your device gives that exception today at 18:33 o'clock?

**Comment by pgdr** [comment]
And PI05 this morning.

**Comment by pgdr** [comment]
And the PI05 was upgraded to 0.16 before that exception.

**Comment by joakim-hove** [comment]
> And the PI05 was upgraded to 0.16 before that exception.

Well - 0.16 has the update bug. The fix is in 0.17. Mine and also the PI05 must actually be resurrected manually, luckily that is PI05 is @njberland sensor.

**Comment by joakim-hove** [comment]
Have set PI10 also to 0.17; but I fear that will need a manual restart.

**Comment by pgdr** [comment]
PI10 has been manually reset.
