### ISSUE TITLE
entered failed state after __str__ returned non-string

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#87]
It looks like the exception `a` that is caught does not implement `__str__` correctly?  Very strange indeed.

Anyway, since we are based on `systemd`, we should simply implement an automatic restart scheme on failure.  The client should be allowed to crash, burn, and die, and `systemd` should restart as necessary.

```
23:12:32 pi fby_client[22687]: Traceback (most recent call last):
23:12:32 pi fby_client[22687]: File "/usr/local/friskby/bin/fby_client", line 143, in <module>
23:12:32 pi fby_client[22687]: fby.run()
23:12:32 pi fby_client[22687]: File "/usr/local/friskby/bin/fby_client", line 118, in run
23:12:32 pi fby_client[22687]: self._config.logMessage('Exception caught: "%s".' % str(a), long_msg = "".join( tb_list ))
23:12:32 pi fby_client[22687]: TypeError: __str__ returned non-string (type Error)
23:12:33 pi systemd[1]: friskby.service: main process exited, code=exited, status=1/FAILURE
23:12:33 pi systemd[1]: Unit friskby.service entered failed state.
```

**Comment by joakim-hove** [comment]
That was indeed peculiar. I agree that systemd should restart - I still think we should _try_ to handle everything.

**Comment by pgdr** [comment]
I agree with should _handle everything we know_ meaning that we shouldn't catch with simply `except:`, but go towards more specific catches; If we don't know what will be thrown, how do we know what to do?

Anyway, I found this/these strange bug report(s):

> kennethreitz/requests#2524 → shazow/urllib3#556

It seems that it might be that the `__str__` implementation of one of the exceptions from Requests is buggy?  That is, in some cases, `__str__` does not return a string, hence the type error.

In any case, the temporary solution we have now might just stay there until it's considered a permanent solution.  We should perhaps add a comment at some point explaining the strange-looking `try`.
