### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#89]
Should we try the following?

2016-12: Python 3-compatibility
2017-02: Experimental runs with Python 3
2017-04: Ditch Python 2 support

**Comment by joakim-hove** [comment]
I support Python3 - I guess it should be possible to use e.g. six and have both for a while.

**Comment by pgdr** [comment]
Time flies like an arrow.

What's people's opinion on this subject?  I think we're pretty close to Python 3 compatibility anyway, with the exception of some renamed modules (urlparse comes to mind).  Should we add six as a prerequisite and slowly start running python with the `-3` flag?

**Comment by pgdr** [comment]
I'm closing this as wontfix
